# Generated by Django 5.1.1 on 2024-10-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_alter_passenger_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
